title: Study Friend
email: your-email@example.com
description: >-
  Study Friend is your AI-powered smart learning partner.
baseurl: ""
url: ""
theme: minima
plugins:
  - jekyll-feed

collections:
  pages:
    output: true
    permalink: /:name/

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page
